script: |
          # Masuk ke folder project
          cd /opt/apps/sik-shineeducationbali

          # PENTING: Paksa server mengikuti versi GitHub (hapus edit manual)
          git fetch --all
          git reset --hard origin/main
          
          # Matikan container lama
          docker compose down

          # Nyalakan ulang dengan build baru
          docker compose up -d --build
          
          # Hapus image sampah (opsional, biar disk gak penuh)
          docker image prune -f